name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: vapor/swiftly-action@v0.2
      - run: |
          swiftly install --assume-yes --use --post-install-file "${HOME}/.swiftly-postinstall-cmds.sh"
          if [[ -f "${HOME}/.swiftly-postinstall-cmds.sh" ]]; then
            if [[ "$(id -un)" == 'root' ]]; then
              env DEBIAN_FRONTEND=noninteractive bash "${HOME}/.swiftly-postinstall-cmds.sh"
            else
              sudo env DEBIAN_FRONTEND=noninteractive bash "${HOME}/.swiftly-postinstall-cmds.sh" # use the current value of HOME, not root's
            fi
            rm "${HOME}/.swiftly-postinstall-cmds.sh"
          fi
      - name: Install Swift WebAssembly SDK
        id: setup-sdk
        run: ./setup-swift-sdk.sh
