name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: vapor/swiftly-action@v0.2
      - run: swiftly install
      - name: Install Swift WebAssembly SDK
        id: setup-sdk
        run: ./setup-swift-sdk.sh
